# Generated by Django 3.2.17 on 2023-02-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20230211_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Картинка'),
        ),
    ]
