# Generated by Django 3.2.17 on 2023-02-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
