# Generated by Django 3.2.17 on 2023-02-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
