# Generated by Django 3.2.17 on 2023-02-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_user_profile_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
