# Generated by Django 3.2.17 on 2023-02-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
