# Generated by Django 3.2.17 on 2023-02-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_author_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('pub_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
